services:
  ml-service-dev:
    image: myapp:0.0.1
    ports:
      - "7216:7216"
    environment:
      APP_ENVIRONMENT: "production"
    networks:
      - backend-dev

  postgres-dev:
    image: postgres:16.3-alpine
    container_name: monitoring-postgres-dev
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: test
      POSTGRES_DB: monitoring
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U monitor -d monitoring"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-dev

  redis-dev:
    image: redis:latest
    container_name: monitoring-redis-dev
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    networks:
      - backend-dev

  rabbitmq-dev:
    image: rabbitmq:3.13-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  backend-dev:
