{
 "title": "Monitoring Machine 7",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Reconstruction Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT created_at, reconstruction_error \nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  },
  {
   "title": "Sensors [-inf, 42]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  created_at, \n  sensor_00,  \n  sensor_06,\n  sensor_07,\n  sensor_08,\n  sensor_09,\n  sensor_10,\n  sensor_12,\n  sensor_13,\n  sensor_15,\n  sensor_18,\n  sensor_39,\n  sensor_41,\n  sensor_42\nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  },
  {
   "title": "Anomaly Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT created_at, anomaly_counter \nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  },
  {
   "title": "Sensors [42, 71]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \n  created_at, \n  sensor_01,  \n  sensor_02,\n  sensor_03,\n  sensor_11,\n  sensor_37,\n  sensor_38,\n  sensor_40,\n  sensor_43,\n  sensor_44,\n  sensor_45,\n  sensor_46,\n  sensor_47,\n  sensor_49\nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  },
  {
   "title": "Sensors [71, 515]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  created_at, \n  sensor_05,  \n  sensor_14,\n  sensor_16,\n  sensor_17,\n  sensor_20,\n  sensor_22,\n  sensor_27,\n  sensor_33,\n  sensor_34,\n  sensor_35,\n  sensor_48,\n  sensor_50,\n  sensor_51\nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  },
  {
   "title": "Sensors [515, 922]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \n  created_at, \n  sensor_04,\n  sensor_19,\n  sensor_21,\n  sensor_23,\n  sensor_24,\n  sensor_25,\n  sensor_26,\n  sensor_28,\n  sensor_29,\n  sensor_30,\n  sensor_31,\n  sensor_32,\n  sensor_36\nFROM monitoring\nWHERE machine_id = 7\nORDER BY id"
    }
   ]
  }
 ]
}