name: ML Model CI

on:
  pull_request:
    paths:
      - ml_model/**

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        working-directory: ml_model
        run: uv sync --all-extras --dev --frozen

      - name: Run tests
        working-directory: ml_model
        run: |
          uv run pytest --junitxml=pytest.xml \
          --cov-report=term-missing:skip-covered \
          --cov=src tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ml_model/pytest-coverage.txt
          junitxml-path: ml_model/pytest.xml
